---
abstract: 'Teng flavor for Amon2'
author:
  - 'Kazuhiro Shibuya'
build_requires: {}
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.0.53, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Amon2-Setup-Flavor-Teng
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
provides:
  Amon2::Setup::Flavor::Teng:
    file: lib/Amon2/Setup/Flavor/Teng.pm
    version: 0.05
  Amon2::Setup::Flavor::TengWithoutLoader:
    file: lib/Amon2/Setup/Flavor/TengWithoutLoader.pm
requires:
  Amon2: 3.53
  Amon2::Plugin::DBI: 0.08
  DBD::SQLite: 1.37
  Teng: 0.15
  perl: 5.008001
resources:
  bugtracker: https://github.com/ka2u/Amon2-Setup-Flavor-Teng/issues
  homepage: https://github.com/ka2u/Amon2-Setup-Flavor-Teng
  repository: https://github.com/ka2u/Amon2-Setup-Flavor-Teng.git
version: 0.05
x_contributors:
  - 'Tokuhiro Matsuno <tokuhirom@gmail.com>'
  - 'memememomo <memememomo@gmail.com>'
  - 'Hiroaki Yoshida <yoshidaster@gmail.com>'
  - 'Kazuhiro Shibuya <stevenlabs@gmail.com>'
