---
abstract: 'Teng flavor for Amon2'
author:
  - 'Kazuhiro Shibuya'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Amon2-Setup-Flavor-Teng
no_index:
  directory:
    - t
    - inc
requires:
  Amon2: 3.53
  DBD::SQLite: 1.37
  Teng: 0.15
  perl: 5.008001
version: 0.04
